<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-15T19:51:42 IST" name="Default suite" finished-at="2024-09-15T19:51:58 IST" duration-ms="16198">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@128d2484]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-09-15T19:51:42 IST" name="Default test" finished-at="2024-09-15T19:51:58 IST" duration-ms="16198">
      <class name="parallel.ParallelRun">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:42 IST" name="setUpClass" finished-at="2024-09-15T19:51:43 IST" duration-ms="1074" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@535b8c24]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:43 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-09-15T19:51:55 IST" duration-ms="12214" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["User should be able to login with valid cred"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Feature"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:43 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-09-15T19:51:55 IST" duration-ms="12277" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["User should be able to login with valid cred"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Feature"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:43 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-09-15T19:51:55 IST" duration-ms="12119" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User should be able to login with valid cred"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Feature"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at parallel.StepDefinition.user_should_login_successfully(StepDefinition.java:35)
at ✽.User should login successfully(classpath:parallel/login2.feature:37)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:43 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-09-15T19:51:55 IST" duration-ms="12057" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User should be able to login with valid cred"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Feature"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at parallel.StepDefinition.user_should_login_successfully(StepDefinition.java:35)
at ✽.User should login successfully(classpath:parallel/login1.feature:37)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:43 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-09-15T19:51:55 IST" duration-ms="12211" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["User should be able to login with valid cred"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Feature"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:43 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-09-15T19:51:55 IST" duration-ms="12131" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User should be able to login with valid cred"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Feature"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://practicetestautomation.com/logged-in-successfully/] but found [https://practicetestautomation.com/practice-test-login/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at parallel.StepDefinition.user_should_login_successfully(StepDefinition.java:35)
at ✽.User should login successfully(classpath:parallel/login1.feature:29)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:parallel.ParallelRun@128d2484]" started-at="2024-09-15T19:51:55 IST" name="tearDownClass" finished-at="2024-09-15T19:51:58 IST" duration-ms="2782" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- parallel.ParallelRun -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
